version: "3.5"

services:
  crawler:
    image: ${REGISTRY}webrecorder/browsertrix-crawler-no-images:latest
    build:
      context: ./

    volumes:
      - ./crawls:/crawls

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

    shm_size: 1gb
